package Vista;

import java.awt.Color;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

public class frmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form frmPrincipal
     */
    public frmPrincipal()
    {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        btnNose.setBackground(new Color(22, 160, 133  ));
        btnIngreso.setBackground(new Color(22, 160, 133    ));
        btnSalida.setBackground(new Color(22, 160, 133  ));
        btnReporte.setBackground(new Color(22, 160, 133  ));
        jPanel1.setBackground(new Color(19, 141, 117  ));
        jMenuBar1.setBackground(new Color(19, 141, 117  ));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnReporte = new javax.swing.JButton();
        btnIngreso = new javax.swing.JButton();
        btnNose = new javax.swing.JButton();
        btnSalida = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        btnMenu = new javax.swing.JMenu();
        btnmenuIngresar = new javax.swing.JMenuItem();
        btnmenuSacar = new javax.swing.JMenuItem();
        btnInformes = new javax.swing.JMenu();
        btnListado = new javax.swing.JMenu();
        btnmenuEstacionados = new javax.swing.JMenuItem();
        btnmenuFacturados = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("          estación de servivio");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 170, 200, 31);

        jPanel1.setBackground(new java.awt.Color(51, 102, 0));
        jPanel1.setForeground(new java.awt.Color(0, 102, 0));

        btnReporte.setBackground(new java.awt.Color(51, 153, 0));
        btnReporte.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        btnReporte.setForeground(new java.awt.Color(255, 255, 255));
        btnReporte.setText("Reporte");
        btnReporte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnReporteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnReporteMouseExited(evt);
            }
        });
        btnReporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReporteActionPerformed(evt);
            }
        });
        jPanel1.add(btnReporte);

        btnIngreso.setBackground(new java.awt.Color(51, 153, 0));
        btnIngreso.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnIngreso.setForeground(new java.awt.Color(255, 255, 255));
        btnIngreso.setText("IN");
        btnIngreso.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnIngreso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnIngresoMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnIngresoMouseExited(evt);
            }
        });
        btnIngreso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresoActionPerformed(evt);
            }
        });
        jPanel1.add(btnIngreso);

        btnNose.setBackground(new java.awt.Color(51, 153, 0));
        btnNose.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnNose.setForeground(new java.awt.Color(255, 255, 255));
        btnNose.setText("Nose");
        btnNose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNoseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNoseMouseExited(evt);
            }
        });
        btnNose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNoseActionPerformed(evt);
            }
        });
        jPanel1.add(btnNose);

        btnSalida.setBackground(new java.awt.Color(51, 153, 0));
        btnSalida.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnSalida.setForeground(new java.awt.Color(255, 255, 255));
        btnSalida.setText("Out");
        btnSalida.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        btnSalida.setBorderPainted(false);
        btnSalida.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnSalida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSalidaMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSalidaMouseExited(evt);
            }
        });
        btnSalida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalidaActionPerformed(evt);
            }
        });
        jPanel1.add(btnSalida);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(230, 0, 300, 230);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/istic.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 225, 225);

        jMenuBar1.setBorder(new javax.swing.border.MatteBorder(null));
        jMenuBar1.setForeground(new java.awt.Color(255, 51, 51));

        btnMenu.setForeground(new java.awt.Color(0, 102, 153));
        btnMenu.setText("Vehiculos");

        btnmenuIngresar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_I, java.awt.event.InputEvent.SHIFT_MASK));
        btnmenuIngresar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnmenuIngresar.setForeground(new java.awt.Color(0, 102, 153));
        btnmenuIngresar.setText("Ingresar");
        btnmenuIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuIngresarActionPerformed(evt);
            }
        });
        btnMenu.add(btnmenuIngresar);

        btnmenuSacar.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.SHIFT_MASK));
        btnmenuSacar.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnmenuSacar.setForeground(new java.awt.Color(0, 102, 153));
        btnmenuSacar.setText("Sacar");
        btnmenuSacar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuSacarActionPerformed(evt);
            }
        });
        btnMenu.add(btnmenuSacar);

        jMenuBar1.add(btnMenu);

        btnInformes.setBackground(new java.awt.Color(255, 255, 255));
        btnInformes.setForeground(new java.awt.Color(0, 102, 153));
        btnInformes.setText("Informes");
        jMenuBar1.add(btnInformes);

        btnListado.setBackground(new java.awt.Color(255, 255, 255));
        btnListado.setForeground(new java.awt.Color(0, 102, 153));
        btnListado.setText("Listado");

        btnmenuEstacionados.setBackground(new java.awt.Color(255, 255, 255));
        btnmenuEstacionados.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnmenuEstacionados.setForeground(new java.awt.Color(0, 102, 153));
        btnmenuEstacionados.setText("Estacionados");
        btnmenuEstacionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnmenuEstacionadosActionPerformed(evt);
            }
        });
        btnListado.add(btnmenuEstacionados);

        btnmenuFacturados.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        btnmenuFacturados.setForeground(new java.awt.Color(0, 102, 153));
        btnmenuFacturados.setText("Facturados");
        btnListado.add(btnmenuFacturados);

        jMenuBar1.add(btnListado);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresoActionPerformed
        frmIngreso objIngreso = new frmIngreso();
        objIngreso.setVisible(true);
    }//GEN-LAST:event_btnIngresoActionPerformed

    private void btnNoseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNoseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNoseActionPerformed

    private void btnSalidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalidaActionPerformed
        frmSalida objSalida = null;
        try {
            objSalida = new frmSalida();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objSalida.setVisible(true);
        objSalida.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnSalidaActionPerformed

    private void btnmenuIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuIngresarActionPerformed
        //System.out.println("Fue presionado");
        frmIngreso objIngreso = new frmIngreso();
        objIngreso.setVisible(true);
        objIngreso.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnmenuIngresarActionPerformed

    private void btnmenuSacarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuSacarActionPerformed
        frmSalida objSalida = null;
        try {
            objSalida = new frmSalida();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objSalida.setVisible(true);
        objSalida.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnmenuSacarActionPerformed

    private void btnmenuEstacionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnmenuEstacionadosActionPerformed
        frmListado objListado = null;
        try {
            objListado = new frmListado();
        } catch (IOException ex) {
            Logger.getLogger(frmPrincipal.class.getName()).log(Level.SEVERE, null, ex);
        }
        objListado.setVisible(true);
        objListado.setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }//GEN-LAST:event_btnmenuEstacionadosActionPerformed

    private void btnReporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReporteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnReporteActionPerformed

    private void btnNoseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoseMouseEntered
        // TODO add your handling code here:
        btnNose.setBackground(new Color(46, 204, 113  ));
        
    }//GEN-LAST:event_btnNoseMouseEntered

    private void btnNoseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNoseMouseExited
        // TODO add your handling code here:
        btnNose.setBackground(new Color(22, 160, 133  ));
        
    }//GEN-LAST:event_btnNoseMouseExited

    private void btnReporteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseEntered
        // TODO add your handling code here:
        btnReporte.setBackground(new Color(46, 204, 113 ));
    }//GEN-LAST:event_btnReporteMouseEntered

    private void btnReporteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnReporteMouseExited
        // TODO add your handling code here:
         btnReporte.setBackground(new Color(22, 160, 133  ));
    }//GEN-LAST:event_btnReporteMouseExited

    private void btnIngresoMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresoMouseEntered
        // TODO add your handling code here:
        btnIngreso.setBackground(new Color(46, 204, 113    ));
    }//GEN-LAST:event_btnIngresoMouseEntered

    private void btnIngresoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnIngresoMouseExited
        // TODO add your handling code here:
        btnIngreso.setBackground(new Color(22, 160, 133    ));
    }//GEN-LAST:event_btnIngresoMouseExited

    private void btnSalidaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaMouseEntered
        // TODO add your handling code here:
        btnSalida.setBackground(new Color(46, 204, 113 ));
    }//GEN-LAST:event_btnSalidaMouseEntered

    private void btnSalidaMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSalidaMouseExited
        // TODO add your handling code here:
         btnSalida.setBackground(new Color(22, 160, 133  ));
    }//GEN-LAST:event_btnSalidaMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu btnInformes;
    private javax.swing.JButton btnIngreso;
    private javax.swing.JMenu btnListado;
    private javax.swing.JMenu btnMenu;
    private javax.swing.JButton btnNose;
    private javax.swing.JButton btnReporte;
    private javax.swing.JButton btnSalida;
    private javax.swing.JMenuItem btnmenuEstacionados;
    private javax.swing.JMenuItem btnmenuFacturados;
    private javax.swing.JMenuItem btnmenuIngresar;
    private javax.swing.JMenuItem btnmenuSacar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
