/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;
import Clases.*;

/**
 *
 * @author PC
 */
public class frmTaquilla extends javax.swing.JFrame {

    //Creación de la instancia SalaCine llamada objSalaCentral
    private SalaCine objSalaCentral = new SalaCine(500,300.0);//esto equivale a pasar los valores al constructor cuando lo ejecuto y se hace solo una vez
    private SalaCine objSalaSecundaria = new SalaCine();
    /**
     * Creates new form frmTaquilla
     */
    public frmTaquilla() {
        initComponents();
        
         objSalaSecundaria.setCapacidad(250);
         objSalaSecundaria.setPrecioEntrada(180.0);//esto equivale a asignar los valores a través de de los metodos set
      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtPeliculaCentral = new javax.swing.JTextField();
        btnEntradaCentral = new javax.swing.JButton();
        btnVaciarCentral = new javax.swing.JButton();
        lblPorcCentral = new javax.swing.JLabel();
        lblTotalCentral = new javax.swing.JLabel();
        lblEspectadores = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        Textsala2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        lblPorcSala2 = new javax.swing.JLabel();
        lblEspectadores2 = new javax.swing.JLabel();
        lblTotalSala2 = new javax.swing.JLabel();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)), "SALA CENTRAL"));

        jLabel1.setText("Película:");

        btnEntradaCentral.setText("Entrada");
        btnEntradaCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntradaCentralActionPerformed(evt);
            }
        });

        btnVaciarCentral.setText("Vaciar");
        btnVaciarCentral.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVaciarCentralActionPerformed(evt);
            }
        });

        lblPorcCentral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPorcCentral.setForeground(new java.awt.Color(255, 102, 0));
        lblPorcCentral.setText("% Ocupación");

        lblTotalCentral.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblTotalCentral.setForeground(new java.awt.Color(0, 102, 102));
        lblTotalCentral.setText("Total $: 0,00");

        lblEspectadores.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblEspectadores.setForeground(new java.awt.Color(204, 0, 0));
        lblEspectadores.setText("Espectadores: 0");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPeliculaCentral, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lblPorcCentral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(btnEntradaCentral)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnVaciarCentral)
                                .addGap(50, 50, 50)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEspectadores)
                            .addComponent(lblTotalCentral))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtPeliculaCentral, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEntradaCentral)
                    .addComponent(btnVaciarCentral)
                    .addComponent(lblEspectadores))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPorcCentral)
                    .addComponent(lblTotalCentral))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 102, 0)), "SALA SECUNDARIA"));

        jLabel2.setText("Pelicula");

        jButton1.setText("Entrada");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Vaciar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        lblPorcSala2.setBackground(new java.awt.Color(51, 51, 255));
        lblPorcSala2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblPorcSala2.setForeground(new java.awt.Color(51, 51, 255));
        lblPorcSala2.setText("% Ocupacion");

        lblEspectadores2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        lblEspectadores2.setText("Espectadores");

        lblTotalSala2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalSala2.setForeground(new java.awt.Color(153, 0, 51));
        lblTotalSala2.setText("Total $: 0,00");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)
                        .addGap(26, 26, 26)
                        .addComponent(Textsala2, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(lblPorcSala2)
                        .addGap(156, 156, 156)
                        .addComponent(lblTotalSala2)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(jButton1)
                .addGap(31, 31, 31)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblEspectadores2)
                .addGap(71, 71, 71))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Textsala2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblEspectadores2)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblPorcSala2)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblTotalSala2)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnEntradaCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntradaCentralActionPerformed
        
        objSalaCentral.ingresarEspectador(1);
        lblEspectadores.setText("Espectadores: " + objSalaCentral.getAsientosOcupados());
        lblPorcCentral.setText("Ocupación del " + objSalaCentral.getPorcOcupacion() + "%");
        lblTotalCentral.setText("Total $:" + objSalaCentral.getTotaldeIngresos());
        //lblTotalCentral.setText("Total $: ");
    }//GEN-LAST:event_btnEntradaCentralActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        objSalaSecundaria.ingresarEspectador(1);
        lblEspectadores2.setText("Espectadores: " + objSalaSecundaria.getAsientosOcupados());
        lblPorcSala2.setText("Ocupación del " + objSalaSecundaria.getPorcOcupacion() + "%");
        lblTotalSala2.setText("Total $:" + objSalaSecundaria.getTotaldeIngresos());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnVaciarCentralActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVaciarCentralActionPerformed
        objSalaCentral.vaciarSala();
        // TODO add your handling code here:
        //objSalaCentral.ingresarEspectador(0);
        lblEspectadores.setText("Espectadores: " + objSalaCentral.getAsientosOcupados());
        lblPorcCentral.setText("Ocupación del " + objSalaCentral.getPorcOcupacion() + "%");
        lblTotalCentral.setText("Total $:" + objSalaCentral.getTotaldeIngresos());
    }//GEN-LAST:event_btnVaciarCentralActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        objSalaSecundaria.vaciarSala();
        // TODO add your handling code here:
        //objSalaSecundaria.ingresarEspectador(-1);
        lblEspectadores2.setText("Espectadores: " + objSalaSecundaria.getAsientosOcupados());
        lblPorcSala2.setText("Ocupación del " + objSalaSecundaria.getPorcOcupacion() + "%");
        lblTotalSala2.setText("Total $:" + objSalaSecundaria.getTotaldeIngresos());
    }//GEN-LAST:event_jButton2ActionPerformed
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmTaquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmTaquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmTaquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmTaquilla.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmTaquilla().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Textsala2;
    private javax.swing.JButton btnEntradaCentral;
    private javax.swing.JButton btnVaciarCentral;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblEspectadores;
    private javax.swing.JLabel lblEspectadores2;
    private javax.swing.JLabel lblPorcCentral;
    private javax.swing.JLabel lblPorcSala2;
    private javax.swing.JLabel lblTotalCentral;
    private javax.swing.JLabel lblTotalSala2;
    private javax.swing.JTextField txtPeliculaCentral;
    // End of variables declaration//GEN-END:variables
}
